language: python
python:
- '3.6'
install:
  - pip install six
  - pip install pytest
  - pip install coveralls
script:
  - coverage run --source=sped_common setup.py test
deploy:
  provider: pypi
  user: ginx
  password:
    secure: "cFaqcB3pvUB/kG4jz6P+x2I9jEhduVg2Kuj36rkWTpsvB2AfLkCNGdj8HeXgzol1oyJ400TovZ6ZyN06tZguBpsaPp+lSY9tWgi4CtpqzDeIxPEGFLO2fIwK+FEjEwZhm+hQxbRuHxI2MfB9gbwnTR+CwSWWllbrzeTezjx9FRbAzBMV5FsJfWFooUJWP64FGpzfO+Jv4VL5OiGgBmIR7g11JO4E9oHldkQdjnDfHfUBkz14TuRLq2dzmZVqRlRyNZEdrTw60e8qdH5ZIs3Kq1UVj8sN17KkkU8ozsR6B0qHlNDV6t2My/Tn6xELgybZ8crPSvU56vzi1NJWvnWG+59hwQDDQuNs5YJRMDhiid28rz+Oa/n96Cbm0ZbBUH3PWaz/cKRfZDGs/eSCUlaelzYT1JUHwNpS5c6NmV48AYVIBcz0O2099CsvAGJMfUfnJ3JLV1XLNdZe65esDSmy9PGQJhr5mYSIg8VIA3Gri3fNZh3MHTCDyXH8iIoYQBHcyZUaE0eHCdid/LCAOs6N9CjrIFo3zSl3BjUv3dpJfKITJhWwiG0/zvl6aJIGbAVQMFXCaQj8ViUK6N4AHDcwFd4mYDgv5C2p83Bx07e9TQ4qhPjEQa4MoebjN6AiRklWTwpxtQc83vs2fwqkn74C9mFdQjIzQGZbOVlsDbW7EbM="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: sped-br/sped-ecd
after_success:
  - coveralls
