language: python
python:
- '3.6'
install:
  - pip install six
  - pip install pytest
  - pip install coveralls
script:
  - coverage run --source=sped_common setup.py test
deploy:
  provider: pypi
  user: ginx
  password:
    secure: "TAjKq1M0eWjMq/ZJ2tuBOYbcLY1v0mwKqRUsrpBJUOgam+4YLQhblPcHLZ3yOV5FzqBxHU/WBByZMloW3Cx5+FYL0MRDmktJTqsM0OjdIqmS5m9+yWIQul8nc/54Aa5lMhXgmDHFrqVV+Noe7nYZ//EetN02DHwx7HN/3lva/Is="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: sped-br/sped-ecd
after_success:
  - coveralls
